// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy6-hCs4cImiSjt5W0Iml4w7bZNxTFrUY',
    appId: '1:695896642159:web:a01c945a6af0e42c33b39a',
    messagingSenderId: '695896642159',
    projectId: 'onspot-8d31f',
    authDomain: 'onspot-8d31f.firebaseapp.com',
    storageBucket: 'onspot-8d31f.appspot.com',
    measurementId: 'G-CQ9D0W8R02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1lOqrVXNVynnrWYZqYMZNEv7VNlzHhmY',
    appId: '1:695896642159:android:5e7c544e45fb26c033b39a',
    messagingSenderId: '695896642159',
    projectId: 'onspot-8d31f',
    storageBucket: 'onspot-8d31f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSHKNb944WFwJdfAH4KxXnIAXn--ivTE0',
    appId: '1:695896642159:ios:77b3cc6d6f96a0c333b39a',
    messagingSenderId: '695896642159',
    projectId: 'onspot-8d31f',
    storageBucket: 'onspot-8d31f.appspot.com',
    iosBundleId: 'com.example.osm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSHKNb944WFwJdfAH4KxXnIAXn--ivTE0',
    appId: '1:695896642159:ios:77b3cc6d6f96a0c333b39a',
    messagingSenderId: '695896642159',
    projectId: 'onspot-8d31f',
    storageBucket: 'onspot-8d31f.appspot.com',
    iosBundleId: 'com.example.osm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy6-hCs4cImiSjt5W0Iml4w7bZNxTFrUY',
    appId: '1:695896642159:web:63784ad92b7da2c733b39a',
    messagingSenderId: '695896642159',
    projectId: 'onspot-8d31f',
    authDomain: 'onspot-8d31f.firebaseapp.com',
    storageBucket: 'onspot-8d31f.appspot.com',
    measurementId: 'G-NEZX2S3MGY',
  );
}
